services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - target: 4200
        published: 4200
        mode: ingress
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 64M
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - target: 3000
        published: 3000
        mode: ingress
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 64M
    command: npm run dev
volumes:
  node_modules:
