port: 4222
monitor_port: 8222

jetstream {
    store_dir: /data/jetstream
    max_mem: 256MB
    max_file: 1GB
}

cluster {
    name: chaos-nats
}

logging {
    debug: false
    trace: false
    logtime: true
    file_size_limit: 10MB
}
