services:
  ui:
    extends:
      file: compose.yaml
      service: ui
    volumes:
      - type: bind
        source: ./ui
        target: /app
    command: ["npm", "run", "dev"]

  mcp-server:
    extends:
      file: compose.yaml
      service: mcp-server
    env_file:
      - ./mcp-server/.env
    volumes:
      - type: bind
        source: ./mcp-server
        target: /wrapper
