# Generated by Django 4.2.21 on 2025-05-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='vector',
            new_name='embedding',
        ),
    ]
