version: "3.8"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
