services:
  web:
    extends:
      file: compose.yaml
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - redis
      - db

  worker:
    extends:
      file: compose.yaml
      service: worker
    command: watchmedo auto-restart -d . -p "*.py" -- celery -A django_celery worker --loglevel=info
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - db

  db:
    extends:
      file: compose.yaml
      service: db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    extends:
      file: compose.yaml
      service: redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
