services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        mode: ingress
    deploy:
      resources:
        reservations:
          memory: 256M
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/
      interval: 30s
      timeout: 10s
      retries: 3
