services:
  app:
    extends:
      file: compose.yaml
      service: app
    ports:
      - target: 5001
        published: 5001
        mode: ingress

  llm:
    extends:
      file: compose.yaml
      service: llm
  # AWS section
    environment:
      - AWS_REGION=${AWS_REGION} # replace with your AWS region
      - AWS_PROFILE=${AWS_PROFILE} # replace with your AWS profile name
      - PROVIDER=aws
    volumes:
      - type: bind
        source: ~/.aws
        target: /root/.aws

  # GCP section
    # environment:
    #   - GCP_PROJECT_ID=${GCP_PROJECT_ID} # replace with your GCP project ID
