# Note: universal image is not compatible with the devcontainer tools.
#       we use the typescript-node image instead here but should switch out per 
#       project requirements. You can choose a devcontainer that's appropriate 
#       for your sample from the list below #REMOVE_ME_AFTER_EDITING

# FROM mcr.microsoft.com/devcontainers/go:1.22-bookworm
# FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm
# FROM mcr.microsoft.com/devcontainers/php:8.3-bookworm
# FROM mcr.microsoft.com/devcontainers/ruby:3.2-bookworm
# FROM mcr.microsoft.com/devcontainers/java:11-bookworm
# FROM mcr.microsoft.com/devcontainers/rust:1-bookworm
FROM mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
