version: "3.9"
name: directus-postgres
services:
  directus:
    extends:
      file: compose.yaml
      service: directus
    environment:
      - SECRET=a-very-secret-key
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
      - DB_CONNECTION_STRING=postgres://directus:directus@postgres:5432/directus
    volumes:
      - /directus/uploads
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: