version: "3.9"
name: directus-postgres
services:
  directus:
    image: directus/directus:10.11.2
    container_name: directus
    ports:
      - target: 8055
        published: 8055
        mode: ingress
    environment:
      - SECRET
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - DB_CLIENT
      - DB_CONNECTION_STRING
      - WEBSOCKETS_ENABLED="true"
