version: "3.9"
name: directus-postgres
services:
  directus:
    image: directus/directus:10.11.2
    ports:
      - target: 8055
        mode: ingress
        published: 8055
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
    environment:
      - SECRET
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - WEBSOCKETS_ENABLED=true

      # Database
      - DB_CLIENT=pg
      - DB_CONNECTION_STRING

      # Redis
      - REDIS
      - CACHE_STORE=redis
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - RATE_LIMITER_STORE=redis
      - SYNCHRONIZATION_STORE=redis

      # Storage
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_BUCKET
      - STORAGE_S3_REGION
      - STORAGE_S3_ENDPOINT

