services:
  app:
    extends:
      file: compose.yaml
      service: app
    environment:
      - DB_URL=postgres://postgres:password@database:5432/postgres
      - DB_SSL=false #set this to true if deploying to defang playground
      - NODE_ENV=development
      - GOOGLE_GENERATIVE_AI_API_KEY=xxx
      - GITHUB_TOKEN=xxx # remove this line if unused

  database:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
