version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  worker:
    build:
      context: ./api
    command: celery -A config worker -l info
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      LLM_MODEL: ai/smollm2
      LLM_ENDPOINT: http://llm/api/v1

  ui:
    build:
      context: ./ui
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - api

  llm:
    provider:
      type: model
      options:
        model: ai/gemma3:1B-Q4_K_M
    x-defang-llm: true
