services:
  postgres:
    extends:
      service: postgres
      file: compose.yaml
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    extends:
      service: redis
      file: compose.yaml

  app:
    extends:
      service: app
      file: compose.yaml
    command: ["./dev.sh"]
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      DJANGO_SECRET_KEY: 5k6qi_gzy65bz2soxl6k(rsrw)0z3ws!zmjzsbe+wkp1ovfayg
    volumes:
      - ./app:/app

  worker:
    extends:
      service: worker
      file: compose.yaml
    volumes:
      - ./app:/app
    command: sh -c "pip install watchdog && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A config worker -l info"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      DJANGO_SECRET_KEY:

  llm:
    extends:
      file: compose.yaml
      service: llm

  embedding:
    extends:
      file: compose.yaml
      service: embedding

volumes:
  pgdata:
