services:
  postgres:
    extends:
      service: postgres
      file: compose.yaml
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    extends:
      service: redis
      file: compose.yaml

  api:
    extends:
      service: api
      file: compose.yaml
    command: ["./dev.sh"]
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      DJANGO_SECRET_KEY:
    volumes:
      - ./api:/app

  worker:
    extends:
      service: worker
      file: compose.yaml
    volumes:
      - ./api:/app
    command: sh -c "pip install watchdog && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A config worker -l info"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/app_db
      DJANGO_SECRET_KEY:

  ui:
    extends:
      service: ui
      file: compose.yaml
    volumes:
      - ./ui:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000

  llm:
    extends:
      file: compose.yaml
      service: llm

  embedding:
    extends:
      file: compose.yaml
      service: embedding

volumes:
  pgdata:
