services:
  platformatic-app:
    build:
      context: .
    ports:
      - target: 3042
        published: 3042
        protocol: tcp
        mode: ingress
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
