# Note: universal image is not compatible with the devcontainer universal image.
#       we use the typescript-node image instead here but should switch out per 
#       project requirements.
FROM mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
