services:
  phoenix:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - MIX_ENV=dev
      - PORT=4000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server_dev