services:
  phoenix:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - target: 4000
        mode: ingress
        published: 4000
    volumes:
      - ./server:/app
    environment:
      - MIX_ENV=dev
      - PORT=4000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defang_dev

volumes:
  postgres_data: