<<<<<<< HEAD
version: "3.9"
=======
>>>>>>> origin/main
name: nextjs-boilerplate
services:
  service1:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
