name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.3
      #REMOVE_ME_AFTER_EDITING - Replace the following line with the list of environment variables you want to pass to the action
      # or remove the lines if you don't need to pass any environment variables/secrets to the action
      with:
        config-env-vars: ENV1 ENV2
      env:
        # Use the GitHub Variables (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables) 
        # to switch between providers. You'll need to make sure to also set the corresponding secrets for the provider you want to use. 
        DEFANG_PROVIDER: ${{ vars.DEFANG_PROVIDER || 'auto' }}
        ENV1: ${{ secrets.ENV1 }}
        ENV2: ${{ secrets.ENV2 }}