name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.2.0
      #REMOVE_ME_AFTER_EDITING - Replace the following line with the list of environment variables you want to pass to the action
      # or remove the lines if you don't need to pass any environment variables/secrets to the action
      with:
        config-env-vars: ENV1 ENV2
      env:
        ENV1: ${{ secrets.ENV1 }}
        ENV2: ${{ secrets.ENV2 }}
