# Sample dev compose file. It can be helpful to provide this kind of file
# for samples where a user may want to hot reload changes in the app, or
# if it depends on stateful services like a database that isn't supported by Defang.

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        mode: ingress
    volumes:
      - ./app:/app
    environment: #REMOVE_ME_AFTER_EDITING
      POSTGRES_URL: postgres://postgres:password@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  postgres_data: