services:
  app:
    restart: unless-stopped
    build:
      context: ./app
    ports:
      - mode: ingress
        target: 8080
    deploy:
      resources:
        reservations:
          memory: 50M
