services:
  jupyter:
    extends:
      service: jupyter
      file: compose.yaml
    environment:
      JUPYTER_TOKEN: jupyter
      POSTGRES_PASSWORD: password
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    
  db:
    extends:
      service: db
      file: compose.yaml
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
