services:
  mongo-express:
    image: mongo-express
    ports:
      - target: 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    x-defang-mongodb: true
    environment:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_ROOT_USERNAME:
