services:
  huginn:
    environment:
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=huginn
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=huginn
      - DATABASE_HOST=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: huginn
      POSTGRES_PASSWORD: huginn
      POSTGRES_DB: huginn
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: