# Sample compose file. #REMOVE_ME_AFTER_EDITING

services:
  app:
    # uncomment to add your own domain
    # domainname: example.com
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        mode: ingress
    environment:
      REDIS_URL: redis://redis_service:6379
      POSTGRES_URL: postgres://postgres:password@postgres_service:5432/postgres
      POSTGRES_PASSWORD: testtest
    healthcheck:
      # wget or curl required for healthchecks on services with a published port
      # this gets parsed by Defang and provided to the load balancers as well
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]

  redis_service:
    image: redis:6.2
    x-defang-redis: true
    ports:
      - mode: host
        target: 6379

  postgres_service:
    image: postgres:16.4
    x-defang-postgres: true
    ports:
      - mode: host
        target: 5432
    environment:
      POSTGRES_PASSWORD: testtest