#REMOVE_ME_AFTER_EDITING
# Sample dev compose file. It can be helpful to provide this kind of file
# for samples where a user may want to hot reload changes in the app, or
# if it depends on stateful services like a database that isn't supported
# by Defang, like MongoDB.

services:
  app:
    extends:
      file: compose.yaml
      service: app
    volumes:
      - ./app:/app
    healthcheck: {}
    depends_on:
      - redis_service

  redis_service:
    extends:
      file: compose.yaml
      service: redis_service

volumes:
  mongo_data: