services:
  app:
    extends:
      file: compose.yaml
      service: app
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run start
