# Use the official Node.js image
FROM node:20-alpine

# Create and change to the app directory
WORKDIR /app

# Copy application dependency manifests to the container image
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the local code to the container image
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Install additional dependencies for development
RUN npm install -g @angular/cli

# Start the Angular app in development mode
CMD ["npm", "start"]
