services:
  ollama:
    extends:
      file: compose.yaml
      service: ollama
    env_file:
      - .env.dev
    volumes:
        - ./ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      # wget or curl required for healthchecks on services with a published port
      # this gets parsed by Defang and provided to the load balancers as well
      test: [ "CMD", "curl", "-s", "http://localhost:11434/" ]
    deploy:
      resources:
        reservations:
          cpus: '2.0'
          memory: 8192M
          # Uncomment the next two lines to enable GPU support, for example to use gemma:7b
          # NOTE: this is only supported in [BYOC](https://docs.defang.io/docs/concepts/defang-byoc)
          # devices:
          #   - capabilities: ["gpu"]

  ui:
    extends:
      file: compose.yaml
      service: ui
    env_file:
      - .env.dev

volumes:
  ollama:
    driver: local
  ollama-entrypoint.sh:
    driver: local