services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M
    #environment:
    #  - API_KEY
    #  - API_SECRET
