# Generated by Django 4.2.21 on 2025-05-26 11:53
from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    operations = [
        VectorExtension(),
    ]
