version: '3.9'
services:
  db:
    image: postgres:15
    init: true
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - mode: host
        target: 5432
        published: 5432
  todo_list:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - mode: ingress
        target: 3000
        published: 3000
    volumes: 
      - "./client:/code"
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - target: 3010
        mode: ingress
        published: 3010
    environment:
      - DB_HOST=db
    volumes:
      - "./server:/app"
    depends_on:
      - db
