name: deploy

on:
  push:
    branches:
      - main
      - pr-test/*

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install defang
      run: . <(curl -Ls https://s.defang.io/install)

    - name: Login to Defang
      run: defang login

    - name: Set config
      run: echo $OPENAI_KEY | defang config set --name OPENAI_KEY
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    - name: Deploy
      run: defang compose up -v --detach
