version: '3.9'
name: fastapi-postgres

services:
  fastapi:
    extends:
      file: compose.yaml
      service: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./fastapi:/app
    depends_on:
      - db
    command: fastapi dev main.py --host 0.0.0.0

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  