name: Trigger Docs Samples Rebuild
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "samples/**"

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v1
        with:
          args: check ./samples

      - name: Run Ruff formatter check
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

  js-ts-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run ESLint (JS/TS only)
        run: npx eslint "samples/**/*.{js,ts,jsx,tsx}"

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: ./samples

  build-json:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CLI Autodoc
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DOCS_ACTION_TRIGGER_TOKEN }}
          repository: DefangLabs/defang-docs
          event-type: sample-update
