name: Trigger Docs Samples Rebuild

on:
  push:
    branches:
      - main
    paths:
      - "samples/**"

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v1
        with:
          args: check ./samples

      - name: Run Ruff formatter check
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"


  build-json:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CLI Autodoc
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DOCS_ACTION_TRIGGER_TOKEN }}
          repository: DefangLabs/defang-docs
          event-type: sample-update
