name: Deploy Changed Samples

on:
  pull_request:
    paths:
      - 'samples/**'

jobs:
  deploy_samples:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      DEFANG_FABRIC: fabric-staging.defang.dev:443
    concurrency:
      group: deploy_samples-group-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Fetch main branch
        run: git fetch origin main:main # Fetch the main branch reference for comparison

      - name: Identify changed samples
        run: |
          echo "Identifying changed samples..."
          bash scripts/changed-samples.sh > changed_samples.txt
          if [ ! -s changed_samples.txt ]; then
            echo "No samples have changed. Exiting..."
            exit 0
          fi

      - name: Clone defang-mvp
        uses: actions/checkout@v3
        with:
          repository: DefangLabs/defang-mvp
          fetch-depth: 1
          ref: jordan/issuetoken
          path: defang-mvp
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install defang
        shell: bash
        run: . <(curl -Lf https://raw.githubusercontent.com/DefangLabs/defang/main/src/bin/install || echo return $?)
        env:
          GH_TOKEN: ${{ github.token }} # avoid rate-limits

      - name: Install gnu parallel
        run: sudo apt-get update && sudo apt-get install parallel

      - name: Deploy Samples
        shell: bash
        env:
          TEST_AWS_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          TEST_AWS_SECRET_KEY: ${{ secrets.TEST_AWS_SECRET_KEY }}
          TEST_BOARD_PASSWORD: ${{ secrets.TEST_BOARD_PASSWORD }}
          TEST_DATABASE_HOST: ${{ secrets.TEST_DATABASE_HOST }}
          TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
          TEST_DATABASE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_DATABASE_USERNAME: ${{ secrets.TEST_DATABASE_USERNAME }}
          TEST_HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.TEST_HASURA_GRAPHQL_ADMIN_SECRET }}
          TEST_HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.TEST_HASURA_GRAPHQL_DATABASE_URL }}
          TEST_HF_TOKEN: ${{ secrets.TEST_HF_TOKEN }}
          TEST_MB_DB_DBNAME: ${{ secrets.TEST_MB_DB_DBNAME }}
          TEST_MB_DB_HOST: ${{ secrets.TEST_MB_DB_HOST }}
          TEST_MB_DB_PASS: ${{ secrets.TEST_MB_DB_PASS }}
          TEST_MB_DB_PORT: ${{ secrets.TEST_MB_DB_PORT }}
          TEST_MB_DB_USER: ${{ secrets.TEST_MB_DB_USER }}
          TEST_NC_DB: ${{ secrets.TEST_NC_DB }}
          TEST_NC_S3_ENDPOINT: ${{ secrets.TEST_NC_S3_ENDPOINT }}
          TEST_NC_S3_BUCKET_NAME: ${{ secrets.TEST_NC_S3_BUCKET_NAME }}
          TEST_NC_S3_REGION: ${{ secrets.TEST_NC_S3_REGION }}
          TEST_NC_S3_ACCESS_KEY: ${{ secrets.TEST_NC_S3_ACCESS_KEY }}
          TEST_NC_S3_ACCESS_SECRET: ${{ secrets.TEST_NC_S3_ACCESS_SECRET }}
          TEST_OPENAI_KEY: ${{ secrets.TEST_OPENAI_KEY }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
          TEST_QUEUE: ${{ secrets.TEST_QUEUE }}
          TEST_SECRET_KEY_BASE: ${{ secrets.TEST_SECRET_KEY_BASE }}
          TEST_SESSION_SECRET: ${{ secrets.TEST_SESSION_SECRET }}
          TEST_SLACK_CHANNEL_ID: ${{ secrets.TEST_SLACK_CHANNEL_ID }}
          TEST_SLACK_TOKEN: ${{ secrets.TEST_SLACK_TOKEN }}
        run: |
          echo "DEFANG_DEBUG=$RUNNER_DEBUG" >> $GITHUB_ENV

          CHANGED_SAMPLES=$(cat changed_samples.txt)
          echo "changed samples"
          echo $CHANGED_SAMPLES

          CONCURRENT_DEPLOYMENTS=8

          for ((i=0; i<${#CHANGED_SAMPLES[@]}; i+=$CONCURRENT_DEPLOYMENTS)); do
            AWS_REGION=us-west-2 AWS_PROFILE=defang-staging TENANT=defangSampleTestFakeTenant$i CLUSTER=$CLUSTER bash scripts/deploy-samples.sh ${CHANGED_FILES[@]:$i:$CONCURRENT_DEPLOYMENTS}
          done
