# FROM mcr.microsoft.com/devcontainers/go:1.22-bookworm
# FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm
# FROM mcr.microsoft.com/devcontainers/php:8.3-bookworm
# FROM mcr.microsoft.com/devcontainers/ruby:3.2-bookworm
# FROM mcr.microsoft.com/devcontainers/java:11-bookworm
# FROM mcr.microsoft.com/devcontainers/rust:1-bookworm
FROM mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
